apiVersion: v1
kind: Service
metadata:
  name: demoservice-{{ .Values.letter}}-{{ .Values.num }}
spec:
  type: ClusterIP
  selector:
    app: demoservice-{{ .Values.letter}}-{{ .Values.num }}
  ports:
    - protocol: TCP
      port: {{ .Values.host_port }}