version: '3'

services:
  mongo:
    image: mongo
    restart: always
    container_name: 'mongo_porus'
    environment:
#      MONGO_INITDB_DATABASE: porus
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - '27017-27019:27017-27019'


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

#  mongodb://root:1234@localhost:27017/admin
