version: '3.4'

services:
#  mongo:
#    image: mongo
#    restart: always
#    container_name: 'mongo_porus'
#    environment:
##      MONGO_INITDB_DATABASE: porus
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: 1234
#    ports:
#      - '27017-27019:27017-27019'

  mongo:
    image: mongo
    restart: always
    container_name: 'mongo_porus'
    hostname: mongodb
    environment:
      #      MONGO_INITDB_DATABASE: porus
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_REPLICA_SET_NAME: rs0
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u root -p 1234 --quiet) -eq 1
      interval: 10s
      start_period: 30s
    ports:
      - '27017-27019:27017-27019'
#    command: ["-f", "/etc/mongod.conf.orig", "--replSet", "r01", "--bind_ip_all"]


#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example

#  mongodb://root:1234@localhost:27017/admin
